package book.discount
import com.cike.drools.entity.Order

rule "book_discount_1"
    when
        $order:Order(originalPrice < 100)
    then
       $order.setRealPrice($order.getOriginalPrice());
       System.out.println("成功匹配到规则一");
end

rule "book_discount_2"
    when
        $order:Order(originalPrice >= 100 && originalPrice<200)
    then
       $order.setRealPrice($order.getOriginalPrice()-20);
       System.out.println("成功匹配到规则二");
end

rule "book_discount_3"
    when
        $order:Order(originalPrice >= 200 && originalPrice<300)
    then
       $order.setRealPrice($order.getOriginalPrice()-50);
       System.out.println("成功匹配到规则三");
end

rule "book_discount_4"
    when
        $order:Order(originalPrice >= 300)
    then
       $order.setRealPrice($order.getOriginalPrice()-100);
       System.out.println("成功匹配到规则四");
end